ignite.settings:
  type: config_object
  label: 'Ignite theme settings'
  mapping:
    ig_body_schema:
      type: string
      label: 'Body theme'
    ig_body_bg_schema:
      type: string
      label: 'Body background'
    ig_navbar_schema:
      type: string
      label: 'Navbar theme'
    ig_navbar_bg_schema:
      type: string
      label: 'Navbar background'
    ig_footer_schema:
      type: string
      label: 'Footer theme'
    ig_footer_bg_schema:
      type: string
      label: 'Footer background'
    ig_top_container:
      type: string
      label: 'Website container type'
    ig_top_container_config:
      type: string
      label: 'Website container type configuration'
