block.settings.text_block:
  type: block_settings
  label: 'Text Block settings'
  mapping:
    text:
      type: mapping
      label: 'Text'
      mapping:
        value:
          type: string
          label: 'Value'
        format:
          type: string
          label: 'Format'
